"""init_alembic

Revision ID: 357569636e89
Revises: baf0ec94038c
Create Date: 2022-03-04 11:08:32.367661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '357569636e89'
down_revision = 'baf0ec94038c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
