"""init_alembic

Revision ID: 362dc32f791e
Revises: b7dd936f602c
Create Date: 2022-03-02 19:52:33.136776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '362dc32f791e'
down_revision = 'b7dd936f602c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
