"""init_alembic

Revision ID: 3ee30d64dd9a
Revises: bc925ca37355
Create Date: 2022-03-07 02:11:19.676905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ee30d64dd9a'
down_revision = 'bc925ca37355'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
