"""init_alembic

Revision ID: 4a3275e80944
Revises: df2266e7b0e2
Create Date: 2022-03-04 21:08:14.134814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a3275e80944'
down_revision = 'df2266e7b0e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
