"""init_alembic

Revision ID: 5155a2ea9c74
Revises: 3ee30d64dd9a
Create Date: 2022-03-07 05:34:59.605899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5155a2ea9c74'
down_revision = '3ee30d64dd9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
