"""init_alembic

Revision ID: 59800a628757
Revises: 357569636e89
Create Date: 2022-03-04 13:30:04.756315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59800a628757'
down_revision = '357569636e89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
