"""init_alembic

Revision ID: 5d0a9abc56ac
Revises: d5b141eb864f
Create Date: 2022-03-04 17:36:36.892721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d0a9abc56ac'
down_revision = 'd5b141eb864f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
