"""init_alembic

Revision ID: 8bb369aa650b
Revises: c03464011c08
Create Date: 2022-03-06 10:01:17.690277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bb369aa650b'
down_revision = 'c03464011c08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
