"""init_alembic

Revision ID: b7470fa1c3b8
Revises: 362dc32f791e
Create Date: 2022-03-03 03:00:38.969748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7470fa1c3b8'
down_revision = '362dc32f791e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
