"""init_alembic

Revision ID: b7dd936f602c
Revises: a81c60b75b04
Create Date: 2022-03-02 19:17:18.958875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7dd936f602c'
down_revision = 'a81c60b75b04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
