"""init_alembic

Revision ID: b7eb56e5ac33
Revises: 59800a628757
Create Date: 2022-03-04 14:31:04.280415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7eb56e5ac33'
down_revision = '59800a628757'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
