"""init_alembic

Revision ID: baf0ec94038c
Revises: d5b141eb864f
Create Date: 2022-03-04 10:07:09.009818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baf0ec94038c'
down_revision = 'd5b141eb864f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
