"""init_alembic

Revision ID: bc41f47a80c3
Revises: d64de0e6cd12
Create Date: 2022-03-05 04:00:08.011948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc41f47a80c3'
down_revision = 'd64de0e6cd12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
