"""init_alembic

Revision ID: bc925ca37355
Revises: 8bb369aa650b
Create Date: 2022-03-06 10:02:09.762328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc925ca37355'
down_revision = '8bb369aa650b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
