"""init_alembic

Revision ID: d64de0e6cd12
Revises: 4a3275e80944
Create Date: 2022-03-05 02:55:17.950881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd64de0e6cd12'
down_revision = '4a3275e80944'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
