"""init_alembic

Revision ID: d6965a3a3862
Revises: b7470fa1c3b8
Create Date: 2022-03-03 06:49:46.385116

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd6965a3a3862'
down_revision = 'b7470fa1c3b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ProductIngredientRelation',
    sa.Column('product_num', sa.Integer(), nullable=True),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['product_num'], ['product.product_num'], )
    )
    op.drop_index('ix_productingredientrelation_id', table_name='productingredientrelation')
    op.drop_index('ix_productingredientrelation_ingredient_id', table_name='productingredientrelation')
    op.drop_index('ix_productingredientrelation_product_num', table_name='productingredientrelation')
    op.drop_table('productingredientrelation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productingredientrelation',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('product_num', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ingredient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], name='productingredientrelation_ibfk_1'),
    sa.ForeignKeyConstraint(['product_num'], ['product.product_num'], name='productingredientrelation_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_productingredientrelation_product_num', 'productingredientrelation', ['product_num'], unique=False)
    op.create_index('ix_productingredientrelation_ingredient_id', 'productingredientrelation', ['ingredient_id'], unique=False)
    op.create_index('ix_productingredientrelation_id', 'productingredientrelation', ['id'], unique=False)
    op.drop_table('ProductIngredientRelation')
    # ### end Alembic commands ###
