"""init_alembic

Revision ID: df2266e7b0e2
Revises: f04b315a5d55
Create Date: 2022-03-04 20:58:53.444933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df2266e7b0e2'
down_revision = 'f04b315a5d55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
