"""init_alembic

Revision ID: f04b315a5d55
Revises: b7eb56e5ac33
Create Date: 2022-03-04 14:57:33.849466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f04b315a5d55'
down_revision = 'b7eb56e5ac33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
